### ISSUE TITLE
Use custom exposed ports and entrypoints in docker-compose 

### ISSUE THREAD

**Issue by arthurzenika** [pockost/docker-shinken#1]
Hi,

am interested to get shinken to work in a docker-compose, have you tried to use docker-compose to customized exposed ports and entrypoints instead of having an image by service ?

**Comment by lermit** [comment]
Hi Arthur,

Thank you for the question.

Yes you can customize the command with a docker compose file like that

```
version: '2'

services:
  arbiter:
    image: pockost/shinken:2.4-webui2-base
    #restart: always
    command: "/usr/bin/shinken-arbiter -c /etc/shinken/shinken.cfg"
    expose:
      - "7770"
    volumes:
      - ./data/shinken/lib:/var/lib/shinken
      - ./config/shinken/etc:/etc/shinken
    networks:
      - back
  poller:
    image: pockost/shinken:2.4-webui2-base
    restart: always
    expose:
      - 7771
    command: "/usr/bin/shinken-poller -c /etc/shinken/daemons/pollerd.ini"
    volumes:
      - ./data/shinken/lib:/var/lib/shinken
      - ./config/shinken/etc:/etc/shinken
    networks:
      - back
  scheduler:
    image: pockost/shinken:2.4-webui2-base
    restart: always
    expose:
      - 7768
    command: "/usr/bin/shinken-scheduler -c /etc/shinken/daemons/schedulerd.ini"
    volumes:
      - ./data/shinken/lib:/var/lib/shinken
      - ./config/shinken/etc:/etc/shinken
    networks:
      - back
  reactionner:
    image: pockost/shinken:2.4-webui2-base
    restart: always
    expose:
      - 7769
    command: "/usr/bin/shinken-reactionner -c /etc/shinken/daemons/reactionnerd.ini"
    volumes:
      - ./data/shinken/lib:/var/lib/shinken
      - ./config/shinken/etc:/etc/shinken
    networks:
      - back
  broker:
    image: pockost/shinken:2.4-webui2-base
    restart: always
    command: "/usr/bin/shinken-broker -c /etc/shinken/daemons/brokerd.ini"
    expose:
      - "7772"
    ports:
      - 8082:7767
    volumes:
      - ./data/shinken/lib:/var/lib/shinken
      - ./config/shinken/etc:/etc/shinken
    networks:
      - front
      - back
  receiver:
    image: pockost/shinken:2.4-webui2-base
    restart: always
    command: "/usr/bin/shinken-receiver -c /etc/shinken/daemons/receiverd.ini"
    ports:
      - 5667:5667
    volumes:
      - ./data/shinken/lib:/var/lib/shinken
      - ./config/shinken/etc:/etc/shinken
    networks:
      - back
  graphite:
    image: sitespeedio/graphite
    restart: always
    ports:
      - "80"
    volumes:
      - ./data/graphite/whisper:/opt/graphite/storage/whisper 
    networks:
      - back
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongo/data:/data/db
    networks:
      - back

networks:
  front:
  back:

```

Hope this will help you ;)

Regards
